/**
 * This file is changed from calculateHealth.py to allow it to work within the TeamStats React component. 
 * The main function, calculateHealthScore, takes in the same data structure as the Python version but is designed to be called within a React useMemo hook for performance optimization. 
 * The scoring logic and metric weights are consistent with the original Python implementation, ensuring that the health score reflects the same underlying principles. 
 * Additionally, helper functions are included to convert raw metric values into a standardized 0-100 scale, which is then combined into an overall health score and status label.
 */

// Metric weights derived from Actionable Steps research
// Weights are kept configurable so they can evolve as research changes
const WEIGHTS = {
    issue_resolution: 0.25,
    issue_responsiveness: 0.20,
    pr_responsiveness: 0.20,
    contributor_activity: 0.15,
    commit_volume: 0.20
};

// Scoring helper functions (convert raw values -> 0-100 scale)
const scoreIssueResolution = (rate) => {
    if (rate >= 0.85) return 100;
    if (rate >= 0.70) return 80;
    if (rate >= 0.50) return 60;
    if (rate >= 0.30) return 40;
    return 20;
};
/**
 * Normalize time-based metrics into a score
 * Used for both issue close time and pull request merge time
 * @param {int} hours 
 * @returns {int} Normalized score between 0 and 100
 */
const scoreTimeHours = (hours) => {
    if (hours <= 24) return 100;
    if (hours <= 72) return 80;
    if (hours <= 168) return 60;
    if (hours <= 336) return 40;
    return 20;
};

/**
 * Scores contributor activity based on number of active contributors
 * @param {int} count 
 * @returns {int} Normalized score between 0 and 100
 */
const scoreContributors = (count) => {
    if (count >= 6) return 100;
    if (count >= 4) return 80;
    if (count >= 2) return 60;
    if (count === 1) return 40;
    return 0;
};

/**
 * Scores commit activity based on total number of commits
 * @param {int} total 
 * @returns {int} Normalized score between 0 and 100
 */
const scoreCommits = (total) => {
    if (total >= 300) return 100;
    if (total >= 150) return 80;
    if (total >= 50) return 60;
    if (total >= 10) return 40;
    return 20;
};
/**
 * Map numerical health score to a qualitative label
 * @param {int} score 
 * @returns {string} Health status label
 */
const healthLabel = (score) => {
    if (score >= 80) return "Healthy";
    if (score >= 50) return "Needs Attention";
    return "Inactive";
};

/**
 * Calculates a repository health score using lifetime repository metrics
 * generated by collectData.py. 
 * @param {Object} data - The repository data
 * @param {Array} activeMetrics - The list of active metrics
 * @returns {Object} The health score and status
 */
export const calculateHealthScore = (data, activeMetrics) => {
    const result = {
        selected_metrics: activeMetrics || [],
        scores: {},
        overall_score: 0,
        status: "Not Enough Data",
        insights: []
    };

    if (!data || Object.keys(data).length === 0 || !activeMetrics || activeMetrics.length === 0) {
        return result; 
    }

    // Storage for raw metric aggregations
    let total_issues_opened = 0;
    let total_issues_closed = 0;
    let issue_close_times = [];

    let pr_merge_times = [];

    let total_commits = 0;
    let active_contributors = 0;

    Object.values(data).forEach(repoData => {
        // Process Issues
        if (repoData.issues) {
            Object.values(repoData.issues).forEach(user_data => {
                const opened = user_data.total_issues_opened || 0;
                const closed = user_data.total_issues_closed || 0;
                const avg_time = user_data.average_time_to_close || 0;

                total_issues_opened += opened;
                total_issues_closed += closed;

                // Only consider contributors who actually closed issues
                if (closed > 0 && avg_time > 0) {
                    issue_close_times.push(avg_time);
                }
            });
        }

        // Process PRs
        if (repoData.pull_requests) {
            Object.values(repoData.pull_requests).forEach(user_data => {
                const avg_time = user_data.average_time_to_merge || 0;
                if (avg_time > 0) {
                    pr_merge_times.push(avg_time);
                }
            });
        }

        // Process Commits
        if (repoData.commits) {
            Object.values(repoData.commits).forEach(user_data => {
                const count = user_data.total_commits || 0;
                total_commits += count;

                // Any contributor with at least one commit is considered active
                if (count > 0) {
                    active_contributors += 1;
                }
            });
        }
    });

    // Compute raw metrics
    const resolution_rate = total_issues_opened > 0 ? (total_issues_closed / total_issues_opened) : 0;
    const avg_close_time = issue_close_times.length > 0 
        ? (issue_close_times.reduce((a, b) => a + b, 0) / issue_close_times.length) 
        : Infinity; // If no issues closed, set to Infinity to reflect poor responsiveness
    
    const avg_merge_time = pr_merge_times.length > 0 
        ? (pr_merge_times.reduce((a, b) => a + b, 0) / pr_merge_times.length) 
        : Infinity; // If no PRs merged, set to Infinity to reflect poor responsiveness

    const metricScores = {
        issue_resolution: scoreIssueResolution(resolution_rate),
        issue_responsiveness: scoreTimeHours(avg_close_time),
        pr_responsiveness: scoreTimeHours(avg_merge_time),
        contributor_activity: scoreContributors(active_contributors),
        commit_volume: scoreCommits(total_commits)
    };

    let total_weighted = 0;
    let total_weights = 0;

    activeMetrics.forEach(metric => {
        const score = metricScores[metric];
        
        if (score !== undefined) {
            result.scores[metric] = score;
            
            const weight = WEIGHTS[metric] || 1;
            total_weighted += score * weight;
            total_weights += weight;
        }
    });

    if (total_weights > 0) {
        result.overall_score = Math.round(total_weighted / total_weights);
        result.status = healthLabel(result.overall_score);
    } else {
        result.overall_score = 0;
        result.status = "Inactive";
    }

    return result;
};